apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic6-agrl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic6-agrl
    app.kubernetes.io/part-of: ec-test-mar-2
  name: devfile-sample-python-basic6-agrl
  namespace: mreid1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic6-agrl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic6-agrl
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:5d98ca21bc3a79e244a17a486a76c82d6dd4aee2f7e1dd3a7aa2e2a962743e58
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
