apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic6-agrl
  namespace: mreid1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:94c18a1d2539b948045eca6c2a138e011822795e2ccf591031f851ec66b31e92
        name: my-python
        resources: {}
status: {}
