apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic6-agrl
  namespace: mreid1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:480f159a72ffb1eaf2579a4d4e5410e3803596339622673dd991063844f76ee5
        name: my-python
        resources: {}
status: {}
